#!/bin/sh
# All regexps are from https://grepbugs.com/browse
#
# The following ones are missing due to being hard to shell-escape:
#
#if\s?\(\s?.*\s?(?<!\!)(?<!=)(?<!<)(?<!>)=(?!=)\s?('|").*('|")\s?\)

for pattern in '\.(html|before|after|append|prepend|appendTo|prependTo)\s*\(' 'ws:\/\/' 'navigator.geolocation.getCurrentPosition' '\.postMessage\s?\(.*\,.*\*.*\)' 'location\.replace' 'localStorage\.' 'Math\.random\s?\(' '\.innerHTML' 'eval\s?\(' 'document\.write'
do
    #echo ">> $pattern"
    #echo
    egrep -r "$pattern" $*
    #echo
done
